"""Simplify Product: use image_url instead of image_filename

Revision ID: 2e485baaf7f0
Revises: c1a3c533a8c5
Create Date: 2025-09-15 11:32:29.868261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e485baaf7f0'
down_revision = 'c1a3c533a8c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=False))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
