"""switch image_filename to image URL

Revision ID: 9c4792418b89
Revises: 541f43254d78
Create Date: 2025-09-19 18:07:11.772782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4792418b89'
down_revision = '541f43254d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=512), nullable=True))
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
