"""Simplify Product: use image_filename instead of image_url

Revision ID: ae1a76cd5b7e
Revises: 2e485baaf7f0
Create Date: 2025-09-15 11:48:49.404523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1a76cd5b7e'
down_revision = '2e485baaf7f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=256), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
